# Generated by Django 5.2.3 on 2025-07-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientes_email_alter_clientes_fecha_and_more'),
        ('detalles_pagos', '0001_initial'),
        ('empleados', '0003_empleados_contraseña'),
        ('fechas_eventos', '0002_fechaseventos_evento'),
        ('materiales', '0002_materiales_marca'),
        ('tematicas', '0003_tematicas_tipo_tematica'),
        ('tipos_eventos', '0002_alter_tiposdeeventos_tipo_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasDeClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('detalle_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detalles_pagos.detallespagos')),
                ('empleado_factura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados')),
                ('fecha_evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fechas_eventos.fechaseventos')),
                ('materiales', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
                ('tematica', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tematicas.tematicas')),
                ('tipo_evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipos_eventos.tiposdeeventos')),
            ],
            options={
                'db_table': 'facturasDeClientes',
            },
        ),
    ]
