# Generated by Django 5.2.3 on 2025-06-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0002_pagos_forma_pago'),
        ('ventas', '0002_ventas_cliente_ventas_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagos.pagos')),
                ('venta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas')),
            ],
        ),
    ]
