# Generated by Django 5.2.3 on 2025-07-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_ventas', '0001_initial'),
        ('ventas', '0002_ventas_cliente_ventas_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesventas',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas'),
        ),
    ]
