# Generated by Django 5.2.3 on 2025-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'materiales',
            },
        ),
    ]
