# Generated by Django 5.2.3 on 2025-06-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='marca',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
