# Generated by Django 5.2.3 on 2025-06-30 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_email_alter_clientes_fecha_and_more'),
        ('empleados', '0003_empleados_contraseña'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleados'),
        ),
    ]
