# Generated by Django 5.2.3 on 2025-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdeeventos',
            name='tipo_evento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
