# Generated by Django 5.2.3 on 2025-06-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Telefono', models.TextField()),
                ('Direccion', models.CharField(max_length=40)),
                ('Ciudad', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=40)),
                ('Fecha', models.DateField()),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
