# Generated by Django 5.2.3 on 2025-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
