# Generated by Django 5.2.3 on 2025-06-30 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formas_pago', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='forma_pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formas_pago.formaspagos'),
        ),
    ]
