# Generated by Django 5.2.3 on 2025-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('Identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=20)),
                ('Telefono', models.TextField()),
                ('Email', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
