# Generated by Django 5.2.3 on 2025-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleados_email_alter_empleados_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='contraseña',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
