# Generated by Django 5.2.3 on 2025-06-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0002_materiales_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='materiales.materiales')),
            ],
            options={
                'db_table': 'compras',
            },
        ),
    ]
