# Generated by Django 5.2.3 on 2025-06-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechas_eventos', '0001_initial'),
        ('tematicas', '0003_tematicas_tipo_tematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaseventos',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tematicas.tematicas'),
        ),
    ]
