# Generated by Django 5.2.3 on 2025-07-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fechas_eventos', '0002_fechaseventos_evento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fechaseventos',
            table='fechasEventos',
        ),
    ]
