# Generated by Django 5.2.3 on 2025-07-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechas_eventos', '0004_alter_fechaseventos_fecha_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaseventos',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
