# Generated by Django 5.2.3 on 2025-06-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tematicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tematica', models.CharField(max_length=20)),
                ('descripcion_tematica', models.TextField()),
            ],
            options={
                'db_table': 'tematicas',
            },
        ),
    ]
