# Generated by Django 5.2.3 on 2025-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tematicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematicas',
            name='nombre_tematica',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
