# Generated by Django 5.2.3 on 2025-06-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tematicas', '0002_alter_tematicas_nombre_tematica'),
        ('tipos_eventos', '0002_alter_tiposdeeventos_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematicas',
            name='tipo_tematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipos_eventos.tiposdeeventos'),
        ),
    ]
